/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/*!
 * @brief
 * Analog switch input control.
 * : For all pins except PIO0_9, PIO0_11, PIO0_12, PIO0_15, PIO0_18, PIO0_31, PIO1_0 and PIO1_9 analog switch is
 * closed (enabled).
 */
#define PIO0_15_ASW_VALUE0 0x00u
/*!
 * @brief
 * Analog switch input control.
 * : For all pins except PIO0_9, PIO0_11, PIO0_12, PIO0_15, PIO0_18, PIO0_31, PIO1_0 and PIO1_9 analog switch is
 * closed (enabled).
 */
#define PIO0_15_ASW_VALUE1 0x01u
/*!
 * @brief Select Digital mode.: Disable digital mode. Digital input set to 0. */
#define PIO0_15_DIGIMODE_ANALOG 0x00u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO0_15_FUNC_ALT0 0x00u
/*!
 * @brief
 * Selects function mode (on-chip pull-up/pull-down resistor control).
 * : Inactive.
 * Inactive (no pull-down/pull-up resistor enabled).
 */
#define PIO0_15_MODE_INACTIVE 0x00u
/*!
 * @brief
 * Analog switch input control.
 * : For all pins except PIO0_9, PIO0_11, PIO0_12, PIO0_15, PIO0_18, PIO0_31, PIO1_0 and PIO1_9 analog switch is
 * closed (enabled).
 */
#define PIO0_16_ASW_VALUE1 0x01u
/*!
 * @brief Select Digital mode.: Disable digital mode. Digital input set to 0. */
#define PIO0_16_DIGIMODE_ANALOG 0x00u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO0_16_FUNC_ALT0 0x00u
/*!
 * @brief
 * Selects function mode (on-chip pull-up/pull-down resistor control).
 * : Inactive.
 * Inactive (no pull-down/pull-up resistor enabled).
 */
#define PIO0_16_MODE_INACTIVE 0x00u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_22_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 7. */
#define PIO0_22_FUNC_ALT7 0x07u
/*!
 * @brief
 * Analog switch input control.
 * : For all pins except PIO0_9, PIO0_11, PIO0_12, PIO0_15, PIO0_18, PIO0_31, PIO1_0 and PIO1_9 analog switch is
 * closed (enabled).
 */
#define PIO0_23_ASW_VALUE1 0x01u
/*!
 * @brief Select Digital mode.: Disable digital mode. Digital input set to 0. */
#define PIO0_23_DIGIMODE_ANALOG 0x00u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO0_23_FUNC_ALT0 0x00u
/*!
 * @brief
 * Selects function mode (on-chip pull-up/pull-down resistor control).
 * : Inactive.
 * Inactive (no pull-down/pull-up resistor enabled).
 */
#define PIO0_23_MODE_INACTIVE 0x00u
/*!
 * @brief
 * Analog switch input control.
 * : For all pins except PIO0_9, PIO0_11, PIO0_12, PIO0_15, PIO0_18, PIO0_31, PIO1_0 and PIO1_9 analog switch is
 * closed (enabled).
 */
#define PIO0_31_ASW_VALUE0 0x00u
/*!
 * @brief
 * Analog switch input control.
 * : For all pins except PIO0_9, PIO0_11, PIO0_12, PIO0_15, PIO0_18, PIO0_31, PIO1_0 and PIO1_9 analog switch is
 * closed (enabled).
 */
#define PIO0_31_ASW_VALUE1 0x01u
/*!
 * @brief Select Digital mode.: Disable digital mode. Digital input set to 0. */
#define PIO0_31_DIGIMODE_ANALOG 0x00u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO0_31_FUNC_ALT0 0x00u
/*!
 * @brief
 * Selects function mode (on-chip pull-up/pull-down resistor control).
 * : Inactive.
 * Inactive (no pull-down/pull-up resistor enabled).
 */
#define PIO0_31_MODE_INACTIVE 0x00u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_4_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO0_4_FUNC_ALT0 0x00u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_5_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO0_5_FUNC_ALT0 0x00u
/*!
 * @brief
 * Selects function mode (on-chip pull-up/pull-down resistor control).
 * : Inactive.
 * Inactive (no pull-down/pull-up resistor enabled).
 */
#define PIO0_5_MODE_INACTIVE 0x00u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_6_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO0_6_FUNC_ALT0 0x00u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_7_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO0_7_FUNC_ALT0 0x00u
/*!
 * @brief
 * Analog switch input control.
 * : For all pins except PIO0_9, PIO0_11, PIO0_12, PIO0_15, PIO0_18, PIO0_31, PIO1_0 and PIO1_9 analog switch is
 * closed (enabled).
 */
#define PIO1_0_ASW_VALUE0 0x00u
/*!
 * @brief
 * Analog switch input control.
 * : For all pins except PIO0_9, PIO0_11, PIO0_12, PIO0_15, PIO0_18, PIO0_31, PIO1_0 and PIO1_9 analog switch is
 * closed (enabled).
 */
#define PIO1_0_ASW_VALUE1 0x01u
/*!
 * @brief Select Digital mode.: Disable digital mode. Digital input set to 0. */
#define PIO1_0_DIGIMODE_ANALOG 0x00u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO1_0_FUNC_ALT0 0x00u
/*!
 * @brief
 * Selects function mode (on-chip pull-up/pull-down resistor control).
 * : Inactive.
 * Inactive (no pull-down/pull-up resistor enabled).
 */
#define PIO1_0_MODE_INACTIVE 0x00u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO1_18_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO1_18_FUNC_ALT0 0x00u
/*!
 * @brief
 * Analog switch input control.
 * : For all pins except PIO0_9, PIO0_11, PIO0_12, PIO0_15, PIO0_18, PIO0_31, PIO1_0 and PIO1_9 analog switch is
 * closed (enabled).
 */
#define PIO1_8_ASW_VALUE1 0x01u
/*!
 * @brief Select Digital mode.: Disable digital mode. Digital input set to 0. */
#define PIO1_8_DIGIMODE_ANALOG 0x00u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO1_8_FUNC_ALT0 0x00u
/*!
 * @brief
 * Selects function mode (on-chip pull-up/pull-down resistor control).
 * : Inactive.
 * Inactive (no pull-down/pull-up resistor enabled).
 */
#define PIO1_8_MODE_INACTIVE 0x00u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO1_9_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO1_9_FUNC_ALT0 0x00u

/*! @name PIO0_4 (number 86), Red
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_led_RED_GPIO GPIO                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_led_RED_GPIO_PIN_MASK (1U << 4U) /*!<@brief GPIO pin mask */
#define BOARD_INITPINS_led_RED_PORT 0U                  /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_led_RED_PIN 4U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_led_RED_PIN_MASK (1U << 4U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*! @name PIO0_6 (number 89), Blue
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_led_BLUE_GPIO GPIO                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_led_BLUE_GPIO_PIN_MASK (1U << 6U) /*!<@brief GPIO pin mask */
#define BOARD_INITPINS_led_BLUE_PORT 0U                  /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_led_BLUE_PIN 6U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_led_BLUE_PIN_MASK (1U << 6U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PIO0_7 (number 6), Green
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_led_GREEN_GPIO GPIO                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_led_GREEN_GPIO_PIN_MASK (1U << 7U) /*!<@brief GPIO pin mask */
#define BOARD_INITPINS_led_GREEN_PORT 0U                  /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_led_GREEN_PIN 7U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_led_GREEN_PIN_MASK (1U << 7U)      /*!<@brief PORT pin mask */
                                                          /* @} */

/*! @name PIO0_5 (number 88), ISP
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_sw_ISP_GPIO GPIO                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_sw_ISP_GPIO_PIN_MASK (1U << 5U) /*!<@brief GPIO pin mask */
#define BOARD_INITPINS_sw_ISP_PORT 0U                  /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_sw_ISP_PIN 5U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_sw_ISP_PIN_MASK (1U << 5U)      /*!<@brief PORT pin mask */
                                                       /* @} */

/*! @name PIO1_9 (number 10), USER
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_sw_USER_GPIO GPIO                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_sw_USER_GPIO_PIN_MASK (1U << 9U) /*!<@brief GPIO pin mask */
#define BOARD_INITPINS_sw_USER_PORT 1U                  /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_sw_USER_PIN 9U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_sw_USER_PIN_MASK (1U << 9U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*! @name PIO1_18 (number 64), WAKE
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_sw_WAKE_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_sw_WAKE_GPIO_PIN_MASK (1U << 18U) /*!<@brief GPIO pin mask */
#define BOARD_INITPINS_sw_WAKE_PORT 1U                   /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_sw_WAKE_PIN 18U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_sw_WAKE_PIN_MASK (1U << 18U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void); /* Function assigned for the Cortex-M33 (Core #0) */

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
